### ISSUE TITLE
Doesn't seem to work with current version of TFS Module

### ISSUE THREAD

**Issue by spreadred** [markwragg/PowerShell-Influx#11]
I have installed your module as well as the TFS Module which you are consuming to make the TFS related calls. 

It seems that the underlying TFS Module relies upon instantiating the following global variable before importing the module (either implicitly or explicitly):

```
$global:tfs=@{
    root_url='https://sometfsserver.com'
    collection='CollectionName'
    project='ProjectName'
}
```

Per your guide at [http://wragg.io/windows-based-grafana-analytics-platform-via-influxdb-and-powershell/](http://wragg.io/windows-based-grafana-analytics-platform-via-influxdb-and-powershell/) you show calling 

`Get-TFSBuildMetric -TFSRootURL 'https://mytfsurl.local/tfs' -TFSCollection somecollection -TFSProject someproject`

However that call does not return as expected since nowhere in the Get-TFSBuildMetric code do you create/set the $global:tfs variable based upon the parameters passed to Get-TFSBuildMetric. Am I not understanding how this should work? Or is this broken due to changes in the underlying TFS Module? If I have to manually create the global variables, what then is the point of the Parameters being passed to Get-TFSBuildMetric?

**Comment by markwragg** [comment]
Thanks for highlighting this, you were absolutely right that`$global:tfs` was not being set by my cmdlet despite me collecting the settings to do so. I think I must have taken it out at some point thinking it was unnecessary.

I've added it in now and have published a new version of the module so give that a go and please reopen this if there are still issues.
