### ISSUE TITLE
Write-Influx multiple Measures

### ISSUE THREAD

**Issue by TheRealNoob** [markwragg/PowerShell-Influx#13]
Thank you for creating this.  It helped me a lot in a pinch.

I spent a few days working on collecting my own metrics and reading write-influx several times over to understand how and why everything was set up the way it was, and one thing became really apparent as a missing feature.  There isn't an ability to send more than one Measure to influx all in one request (mostly impacting TCP since it's so much slower).  If you are storing all of your data in one Measure then there's no issue, but I doubt that's the case for many people.  And since Influx supports accepting more than one measure in a single TCP packet, this certainly seems do-able.

I was wondering if this is something you've ever looked at or worked on?  I was about to start on a PR for it when someone convinced me that I better check with the author first to see if this is something he would even commit.

**Implementation**
I was thinking of adding a function like 'Append-InfluxQueue' (or Add-...) which appends data onto a list.  Basically all of the params like InputObject, Measure, Metrics, and Tags would be moved from Write-Influx onto Append-InfluxQueue and Write-Influx would become a simple writer (also looping through the list turning it into text).  The same is true for UDP as well of course.

Thoughts on this?

P.S. Ever considered building in some windows metrics collectors?

**Comment by markwragg** [comment]
Someone raised this before actually (#7) but they never came back so I closed it. It shouldn't be too tricky to implement. I don't think a second cmdlet should be necessary as the existing `Write-Influx` cmdlet already handles collections of measures, it just then processes them one at a time. Previously I proposed just adding a `-Bulk` switch that would then compile them and send them in one hit to Influx. I'll have a look at doing that today.

And having some pre-written Windows metrics collectors is a great idea. I'll see if I can knock something up, or feel free to contribute something via PR.

**Comment by TheRealNoob** [comment]
my first thought was also to modify the existing write-influx cmdlet but i felt like it would change the cmdlet too drastically.  How are you thinking about implementing accepting multiple measures?  These are some of the solutions I saw and why I decided I didn't like them.  If you see a better way or a flaw in my thinking I welcome it.
- An Array of Measures - How would you keep track of which measures belong to which InputObject hashes.  Someone could submit a length 30 hashtable and 2 Measures.
- Measure becomes Mandatory=False and Bulk required an array with 4 fields titled Measure, Metrics, Tags, InputObject.  This works, except it puts more work on the user.  This is actually the same thing that Append-InfluxQueue would have done for the user.
- Allowing the user to run write-influx many times, each time appending more info to the queue, with the final command having a -Send param to say transmit the payload.  I like this idea, it's simple for the user.  It still makes a complex cmdlet with params that overlap eachother (if -Bulk is used, error on -Measure, -Tags, -InputObject, -Metrics)

You'd have to change the way that Write-Influx works quite a bit.  Given the complexity of accepting both one measure and multiple measures and sending TCP all in one cmlet i felt that adding a second cmdlet to handle some of that was the right move.

Also I've done quite a bit on windows metrics collectors but the performance isn't anywhere near what I was hoping for.  I can open another issue to discuss it, but I can't to be working on two PRs at once at the moment.

**Comment by markwragg** [comment]
I've now added a `-Bulk` switch to `Write-Influx` that when used will transmit all metrics via a single HTTP call at the end. It looks to work correctly via testing, but I don't have an Influx system that I can test against at the moment so have a play with it and let me know if you see any issues.

The feature is available from version 1.0.87 of the module in the PSGallery, so run `update-module influx` and you should have it.

I've also added another cmdlet that I thought might be useful. It's called `ConvertTo-Metric` and you can use it to convert specified properties of any PowerShell object in to the `[metric]` object type that `Write-Influx` can handle via its pipeline.

For example, you can do `Get-Process | ConvertTo-Metric -Measure Process -MetricProperty CPU -TagProperty Name` and you'll get back a collection of PowerShell Objects with Measure, Metric and Tag properties. The result of this can then just be piped to any of `Write-` cmdlets to transmit in to Influx.

I thought this might be a useful way to enable people to transmit metrics for any object data without having to write `Send-` cmdlets as I have for some technologies (although I think these are still useful as they simplify things even further).

Have a play with this also if you think its useful and let me know how it goes.

**Comment by markwragg** [comment]
FYI I didn't see your earlier reply when I replied above. I think your concerns were perhaps somewhat already addressed by the design of the cmdlet, because it currently accepts an object of type `[metric]` or input via parameters. When you send collections of metric objects it was just iterating through them and transmitting them one at a time, where as now if you use `-Bulk` it will do a transmit at the end. I think the `ConvertTo-Metric` cmdlet then compliments this because it allows you to use this cmdlet to "stage" your data into an array of measures (much like the cmdlet you were proposing) before you transmit it. By using this, you can also have a mixture of different measures/tags and still transmit them at once.

**Comment by TheRealNoob** [comment]
I haven't had a chance to look at ti yet but you're right.  Append-InfluxQueue would have just built an array so, it's kind of the same as ConvertTo-Metric, so I'm perfectly fine with it.  I'll try to look at it today and let you know.  Maybe we shouldn't have commited a change though before we've had a chance to test it?

**Comment by markwragg** [comment]
I felt it was OK as its adding new functionality and shouldn't have broken any of the existing functionality. I have tested it with unit tests, I just haven't had a chance to do any integration testing. Although, I've written some Terraform this week that stands up a Windows Influx/Grafana server in AWS so now I can :) : https://github.com/markwragg/Terraform-MetricStack

**Comment by markwragg** [comment]
Closing this, please reopen if you think more discussion is needed.
