### ISSUE TITLE
Force INT / Strings

### ISSUE THREAD

**Issue by arag0nes** [markwragg/PowerShell-Influx#14]
Is there a way to force the format of sent requests to be an Integer or a String? Im having some issues when some of my values are a mixed of INT / String's like this when doing a ForEach loop.

The JobName Var sometimes has values that start like 00250-Name. I I know with influx I can do an "I" or a double quote 

```
$JobName =$_.BackupJobName
$Date =$_.Date
$Name =$_.Name
$Status =$_.Status

Write-Influx -Measure backup_info -Tags @{VMname=$Name} -Metrics @{Date=$Date;Status=$Status;JobName=$JobName} -Database it-stats -Server http://pap-graf01:8086 -Verbose
```

**Comment by markwragg** [comment]
Certainly on the PowerShell side you could just strongly type the variables. I'm not sure whether Influx would respect that on receipt though. Here's what I mean (i've put the hashtable in to a separate variable just for clarity, there's no need to do this to add the type declarations):

```
$Metrics = @{
    Date    = [datetime]$Date
    Status  = [int]$Status
    JobName = [string]$JobName
}

Write-Influx -Measure backup_info -Tags @{VMname = $Name} -Metrics $Metrics -Database it-stats -Server http://pap-graf01:8086 -Verbose
```

**Comment by arag0nes** [comment]
I'll give that a try and see how that works out, thanks!
