### ISSUE TITLE
when property have no value do not send property=""

### ISSUE THREAD

**Issue by Tonic8** [markwragg/PowerShell-Influx#15]
Hello

thanks for the work done :). I have now a limitation:

some object property can have null value, the problem is that when this property is exported there will be conflict on the type of data.

Example with Citrix Xendesktop Powershell sdk, what is actually sent:
```
Xendesktop,computer1 brokeredTime=7, CatalogName="USA1_aa" 12345678898
Xendesktop,computer1 brokeredTime="", CatalogName="USA1_aa" 12345678898
```

the data is either int or string :)

it could be cool to have a option to set write-influx -emptyValueDoNotsent (please find something better for the name of the option :) ), with a result of:

```
Xendesktop,computer1 brokeredTime=7, CatalogName="USA1_aa" 12345678898
Xendesktop,computer1 CatalogName="USA1_aa" 12345678898

```

In this case, zero would not work as the field with no data represent something:
- no data mean no event -> useful to check if a ressource is used or not
- 0 representing user connected in the last hour

Thanks
Tonic8

**Comment by markwragg** [comment]
Hi Tonic8,

I've just added a `-ExcludeEmptyMetric` switch to both `Write-Influx` and `Write-InfluxUDP`. If you install the latest version of the Influx module from the PSGallery you should then have it.

It doesn't work exactly as you show above. As the cmdlet sends each metric individually, if the use the switch and the metrics value is null or empty then it won't be transmitted (vs what I think you're showing above which is a measure being transmitted with tags but no metric when its empty, which I don't think would make sense).

Anyway please test it and let me know if it meets your need. 

Thanks,
Mark

**Comment by Tonic8** [comment]
Hello thanks for the rapid action.

yes not sending the data is the good option (and what i tried to explain). My explanation, is because until now i created one line multiple field, where you send one field per line

when using the new parameter, it work. but i need to do more test. I will try to do the tests with real data ASAP

some things/suggestions:
- if a field in an object is a DateType, you can convert it in something InfluxDB will understand:
```
(dir | select -first1).lastWriteTime | gm
(dir | select -first1).lastWriteTime | get-date -f "yyyy-MM-dd HH:mm:ss.fff"
(dir | select -first1).lastWriteTime | convertTo-UnixTimeNanoseconds
```
where fff is millisecond, (talked here https://stackoverflow.com/questions/28589520/how-to-store-dates-in-influxdb) and here https://docs.influxdata.com/influxdb/v1.5/query_language/data_exploration/#time-syntax


- if a field in an object is something not a "string" but a internal field, like this in Citrix sdk (extract of get-brokerSession | GM):
```
ConnectionViaIP   NoteProperty string ConnectedViaIP=1.2.3.4
ConnectionMode    NoteProperty Citrix.Broker.Admin.SDK.ConnectionMode ConnectionMode=Brokered
```
- if you pass it, the conversion is going wrong(missing doublequote), user must prepare the field, to convert it as string, before passing it to  convertTo-Metric
- example with a Boolean field (it should have double-quote), 
`$test = New-Object PSObject -Property @{testBoolean=$True}`
- below the result from the Write-Influx commande in Verbose
`Xendesktop,computer1 testBoolean=true 12345678898`

**Comment by markwragg** [comment]
I've split your further suggestions above in to their own issue #16

**Comment by Tonic8** [comment]
on the last import with -ExcludeEmptyMetric, work perfect!!
thanks
