### ISSUE TITLE
Improve debug possibilities in write-influx function

### ISSUE THREAD

**Issue by Tonic8** [markwragg/PowerShell-Influx#17]
Hello

on my last usages i got "random" errors in the result formatting. When sending thousands of lines it's hard to see which line got a return HTTP error  400.

It could be useful to get a error debug possibility, like write errors in a file (the data sent and the error code sent back)
like a try and catch and send the data to a variable we can then write in a log file when needed.

Tonic8
(sorry as i'm a newbie on GitHub i don't know how to set this as "enhancement" and not an issue)

**Comment by markwragg** [comment]
Sorry for taking so long to review this. I don't think there's anything to add though at this time. I did consider adding some additional `Write-Verbose` statements but I don't think they'll give much additional value than you already get when running `Write-Influx` with `-Verbose` or `-Debug`. Failing calls to `Invoke-RestMethod` should surface errors automatically. If you have any specific suggestions for enhancements for this please reopen.
