### ISSUE TITLE
Module try to write line with empty tag value

### ISSUE THREAD

**Issue by Tonic8** [markwragg/PowerShell-Influx#20]
Hello

i finally catch the issue i saw with some data, here the data sent 
`xdsession,desktopgroupename=spain-prod,PowerState=On,launchedViaHostName=,hypervizor=vcenter1 LogonInProgress="False"`

"launchedViaHostname=" had not value, and all the line is not written to the DB.

it should be usefull to not send the empty tag.
REgards
Tonic8

**Comment by Tonic8** [comment]
Hello

here is the solution, replace :
```
if ($MetricObject.Tags) {
    $TagData = foreach ($Tag in $MetricObject.Tags.Keys) {
        "$($Tag | Out-InfluxEscapeString)=$($MetricObject.Tags[$Tag] | Out-InfluxEscapeString)"
    }
    $TagData = $TagData -Join ','
    $TagData = ",$TagData"
}
```
by

```
if ($MetricObject.Tags) {
    $TagData = foreach ($Tag in $MetricObject.Tags.Keys) {
		if ([string]::IsNullOrEmpty($MetricObject.Tags[$Tag])) {
			Write-Verbose "$Tag skipped as the value is null or empty, and it's forbiden in InfluxDB."
		}
		else {
			"$($Tag | Out-InfluxEscapeString)=$($MetricObject.Tags[$Tag] | Out-InfluxEscapeString)"
		}
    }
    $TagData = $TagData -Join ','
    $TagData = ",$TagData"
}
```
Regards
Tonic8

i will try this change in my environement next week.

**Comment by Tonic8** [comment]
hello

the change work fine.

**Comment by markwragg** [comment]
Suggested fix implemented. Thanks for your contribution!
