### ISSUE TITLE
write-influx: using $inputObject, we can't use Timestamp parameter

### ISSUE THREAD

**Issue by Tonic8** [markwragg/PowerShell-Influx#23]
Hello

using an inputobject (generated by ConvertTo-Metric), we can't specify a timestamp (PSDate).
Consequence the timestamp it'sq when the command is executed

so in a script if we execute 3 time convertto-metric and write-influx, because we collect the data from 3 different source, the timestamp will vary between the 3 collect.

Regards
Tonic8

**Comment by jrykowski-huron** [comment]
Was able to use -Timestamp with YYYY-MM-DDThh:mm:ss.zzzZ format value and Influx recognized correctly.  Each measure was recorded as unique.
