### ISSUE TITLE
Feature Request: Output to console

### ISSUE THREAD

**Issue by bchris999** [markwragg/PowerShell-Influx#25]
Hi,
Would it be possible to add something to Write-Influx where instead of writing to the database, it outputs in the line protocol format that could be utilised by Telegrafs exec plugin?
I am writing various scripts right now and looking for an easy way to switch them between running under Task Scheduler (ie. direct to DB) and under Telegraf.
Thanks

**Comment by markwragg** [comment]
Yep this shouldn't be too difficult to implement. Feel free to fork and contribute if you're able, otherwise i'll take a look when I have some time.

**Comment by markwragg** [comment]
I've just added a `ConvertTo-InfluxLineString` cmdlet to the module that outputs strings in the Influx line format. Could you try it out and let me know if its what you were looking for?

You need to update the module to version 1.0.96 or later to get the cmdlet.

Example usage:

```
ConvertTo-InfluxLineString -Measure WebServer -Tags @{Server = 'Host01'} -Metrics @{CPU = 100; Status = 'PoweredOn'} -Timestamp (Get-Date)
```

Output:

```
WebServer,Server=Host01 CPU=100 1553005045511021568
WebServer,Server=Host01 Status="PoweredOn" 1553005045511021568
```

**Comment by markwragg** [comment]
Closing, reopen if any changes needed.
