### ISSUE TITLE
Empty Metric gets (wrong) value

### ISSUE THREAD

**Issue by GWS65** [markwragg/PowerShell-Influx#28]
Hello Mark,

Many thanks for your development of the InfluxDb module.  It is the best by far and makes working with Influx from scripts a lot easier.

I ran into this behaviour that I would like to verify because it is different from the intention.
Expected -ExcludeEmptymetric to not pass Metric TestValue but in my test it received the value of 38 (Same as Metric 'Mem')

Thanks,
GWS65

***************  Test *******************

$Tags = @{
    Server2 = 'ServerTag2'
    Location = 'Anywhere'
}

$Metrics = @{
    CPU = 44
    Mem = 38
    TestValue = $null
}

$InfluxLine = ConvertTo-InfluxLineString -Measure WebServer -Tags $Tags -Metrics $Metrics -ExcludeEmptyMetric

**Comment by markwragg** [comment]
This might have been broken by some changes that were implemented in the latest version. Can you let me know what version of the module you’re using?

Thanks,
Mark

**Comment by GWS65** [comment]
Hello Mark, 
I am using the most recent one v1.0.99.

Thanks,
GW

**Comment by GWS65** [comment]
Mark,

Did some further testing using your test script....
$MeasureObject = @(
                [PSCustomObject]@{
                    Name = 'Object1'
                    SomeVal = 1
                    OtherVal = ''
                },
                [PSCustomObject]@{
                    Name = 'Object2'
                    SomeVal = $null
                    OtherVal = 2
                }
            )
$MeasureObject

$WriteInflux = $MeasureObject | ConvertTo-Metric -Measure Test -MetricProperty Name,SomeVal,OtherVal | ConvertTo-InfluxLineString -ExcludeEmptyMetric -Verbose
$WriteInflux
Shows:
Test SomeVal=1,Name="Object1",OtherVal="Object1"
Test SomeVal="Object1",Name="Object2",OtherVal=2

Looks like previously assigned value is used for an empty one.

Reading this again I think the issue should be rephrased. I was expecting the -ExcludeEmptyMetric switch to cause empty fields or tags to be filtered out. that might not be what you intended.

The noted behavior is unexpected though. Properties are assigned wrong values.
I believe that at least leaving out some fields if their value is $null is valid. For tags I am not sure.

Thanks,
GWS65

**Comment by Trovalo** [comment]
Hi, I'm the guy who caused this issue (in my last PR), the "ExcludeEmptyMetric" case was not considered by my changes. (and unfortunately not totally fixed by mark before the merge)
I've just opened a PR to fix this issue, also some tests have been added in order to prevent this issue in the future.
