### ISSUE TITLE
Issue uploading and strange behaviour using -Whatif

### ISSUE THREAD

**Issue by GWS65** [markwragg/PowerShell-Influx#30]
Hello Mark,

Was using Write-Influx successfully to upload data to local InfluxDb 1.7.9. on Windows.

Used the same command to upload to remote server (Unix & cloud based using https and authentication) which did not work. FOr testing I tried -Whatif and saw this unexpected output:
The unexpected thing is that I see multiple lines (one for each Metric value where I was expecting multiple columns and only one line/record. This behaviour was the same for localhost and remote server. Still not sure why remote does not work (Error 400).
Is this an issue with the -Whatif statement or is it really sending out one line per Metric (that would be very ineffecient in regard to DB updates and traffic)

PS C:\Users\> Write-Influx -Measure $Measurement -Tags $Tags -Metrics $Metrics -TimeStamp $InfluxTimeStampUTC -Database $Database -Server http://localhost:8086 -whatif
What if: Performing the operation "azo,ChargeID=428569,RunID=51-000022,WorkCtr=0551,Shift_ID=2020-01-27.07,Shift=O,ShopfloorDatum=2020-01-27 ChargeStart="2020-01-27 08:09:03" 1580108943000000000
azo,ChargeID=428569,RunID=51-000022,WorkCtr=0551,Shift_ID=2020-01-27.07,Shift=O,ShopfloorDatum=2020-01-27 Recipe="S41351v1/2" 1580108943000000000
azo,ChargeID=428569,RunID=51-000022,WorkCtr=0551,Shift_ID=2020-01-27.07,Shift=O,ShopfloorDatum=2020-01-27 Weight_pv=0.499 1580108943000000000
azo,ChargeID=428569,RunID=51-000022,WorkCtr=0551,Shift_ID=2020-01-27.07,Shift=O,ShopfloorDatum=2020-01-27 Weight_sv=0.5 1580108943000000000
azo,ChargeID=428569,RunID=51-000022,WorkCtr=0551,Shift_ID=2020-01-27.07,Shift=O,ShopfloorDatum=2020-01-27 ChargeEnd="2020-01-27 08:22:11" 1580108943000000000
azo,ChargeID=428569,RunID=51-000022,WorkCtr=0551,Shift_ID=2020-01-27.07,Shift=O,ShopfloorDatum=2020-01-27 RecipeName="Middenlaag B" 1580108943000000000
azo,ChargeID=428569,RunID=51-000022,WorkCtr=0551,Shift_ID=2020-01-27.07,Shift=O,ShopfloorDatum=2020-01-27 ArticleID="G10236" 1580108943000000000
azo,ChargeID=428569,RunID=51-000022,WorkCtr=0551,Shift_ID=2020-01-27.07,Shift=O,ShopfloorDatum=2020-01-27 ArticleDesc1="101395" 1580108943000000000" on target "http://localhost:8086/write?&db=afp".

PS C:\Users\> $Metrics
Name                           Value                                                                                                                                                                        
----                           -----                                                                                                                                                                        
ChargeStart                    2020-01-27 08:09:03                                                                                                                                                          
Recipe                         S41351v1/2                                                                                                                                                                   
Weight_pv                      0,499                                                                                                                                                                        
Weight_sv                      0,5                                                                                                                                                                          
ChargeEnd                      2020-01-27 08:22:11                                                                                                                                                          
RecipeName                     Middenlaag B                                                                                                                                                                 
ArticleID                      G10236                                                                                                                                                                       
ArticleDesc1                   101395                                                                                                                                                                       

PS C:\Users\> $Tags

Name                           Value                                                                                                                                                                        
----                           -----                                                                                                                                                                        
ChargeID                       428569                                                                                                                                                                       
RunID                          51-000022                                                                                                                                                                    
WorkCtr                        0551                                                                                                                                                                         
Shift_ID                       2020-01-27.07                                                                                                                                                                
Shift                          O                                                                                                                                                                            
ShopfloorDatum                 2020-01-27

**Comment by markwragg** [comment]
Sorry for the delay responding to this. It is the default behaviour of the `Write-Influx` cmdlet to trasmit each metric individually as you can see in the WhatIf output. There is however a `-Bulk` switch on `Write-Influx` that can be used if you want to transmit via a single connection.

The 400 error you're getting sounds like an authentication issue to me. The module should work the same against remote servers vs local ones.
