### ISSUE TITLE
Write-Influx Fails to write zero values

### ISSUE THREAD

**Issue by mutl3y** [markwragg/PowerShell-Influx#5]
Hi, Trying to send zeros using Write-Influx fails as it drops that part of the hash, simple example below.

Many thanks for writing this great module

Write-Influx -Measure WebServer -Tags @{Server='Host01'} -Metrics @{**CPU=100; Memory=50**} -Database db1 -Server http://127.0.0.1:8086 -Verbose

VERBOSE: Performing the operation "**WebServer,Server=Host01 CPU=100 
WebServer,Server=Host01 Memory=50** " on target "http://127.0.0.1:8086/write?&db=db1 ".
VERBOSE: POST http://127.0.0.1:8086/write?&db=db1 with -1-byte payload
VERBOSE: received -1-byte response of content type application/json

Write-Influx -Measure WebServer -Tags @{Server='Host01'} -Metrics @{**CPU=100; Memory=0**} -Database db1 -Server http://127.0.0.1:8086 -Verbose

VERBOSE: Performing the operation "**WebServer,Server=Host01 CPU=100** " on target "http://127.0.0.1:
8086/write?&db=db1 ".
VERBOSE: POST http://127.0.0.1:8086/write?&db=db1 with -1-byte payload
VERBOSE: received -1-byte response of content type application/json

Same command just removed the 5 from the memory parameter on 2nd run

**Comment by markwragg** [comment]
Thanks for the detailed report, I’ll take a look tomorrow :)

**Comment by markwragg** [comment]
This should be fixed now. If you installed the module via PSGallery you can update to the latest/fixed version via `Update-Module Influx`.

Thanks again for reporting!

**Comment by mutl3y** [comment]
Thanks for letting me know mark
