### ISSUE TITLE
Batch inserts

### ISSUE THREAD

**Issue by OsirisDBA** [markwragg/PowerShell-Influx#7]
It appears that this module only lets you submit a single data point at a time. Is there a method to insert multiple points per request?

Perhaps accept an object in this format : @{ Measure = ''; Tags = @{}; Metrics = @{}; TimeStamp = '' }

**Comment by markwragg** [comment]
The `Write-Influx` cmdlets should process collections of metric objects. This is what the `Get-` cmdlets generally produce. For example, you could do this:

```
$MyMeasures = 1..10 | ForEach-Object {
    [pscustomobject]@{
        PSTypeName = 'Metric'
        Measure    = "MyMeasure"
        Tags       = @{ Server = 'someserver' }
        Metrics    = @{ SomeMetric = $_ }

    }
}

$MyMeasures | Write-Influx
```

It would still send them as 10 individual writes to Influx, but I think thats a limitation on the Influx side. 

You can however have as many metrics as you like in the Metrics hashtable, and in that way you can also submit multiple datapoints at once (for a single measure).

For example:
```
Write-Influx -Measure 'SomeMeasure' -Metrics @{ CPU = 10; Memory = 100 }
```

Influx supports receiving this as a single submission, each metric is separated on a new line for it to distinguish.

**Comment by OsirisDBA** [comment]
Sending 10 individual writes to Influx is what I'd like to avoid. It's
possible to insert multiple measures at once.

https://docs.influxdata.com/influxdb/v1.5/guides/writing_data/#writing-multiple-points

**Comment by markwragg** [comment]
What’s the use case?

You could specify the time stamp if you wanted to ensure they were all written with the same time entry.

I could add a -bulk switch I guess, but the risk would be people submitting too large requests and hitting timeouts potentially. I’m also not sure how beneficial it is as functionality.
